// Regenerate the legacy UI source adapter after editing lib/l10n/app_en.arb:
//   dart run tool/generate_mobile_text.dart
// Then run: flutter gen-l10n
import 'dart:convert';
import 'dart:io';

const _pluralSources = <String, String>{
  '{value1} trip{value2}': 'mobilePluralTrips',
  '{value1} blocked vehicle{value2} excluded.': 'mobilePluralBlockedVehicles',
  '{value1} vehicle{value2} selected': 'mobilePluralSelectedVehicles',
  '{value1} User{value2}': 'mobilePluralUsers',
  '{value1} active day{value2}': 'mobilePluralActiveDays',
  '{value1} result{value2}': 'mobilePluralResults',
  '{value1} vehicle{value2}': 'mobilePluralVehicles',
  '{value1} point{value2}': 'mobilePluralPoints',
};

String _quote(String text) =>
    "'${text.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$').replaceAll('\n', r'\n')}'";

void main() {
  final root = File.fromUri(Platform.script).parent.parent;
  final catalog =
      jsonDecode(File('${root.path}/lib/l10n/app_en.arb').readAsStringSync())
          as Map<String, dynamic>;
  final unique = <String, String>{};
  for (final entry in catalog.entries) {
    if (!entry.key.startsWith('@')) {
      unique.putIfAbsent(entry.value as String, () => entry.key);
    }
  }
  final lines = <String>[
    '// Generated by tool/generate_mobile_text.dart from the ARB catalogs.',
    '// This adapter is for authored UI text; server and user data stay unchanged.',
    "import 'package:flutter/material.dart';",
    '',
    "import '../../l10n/app_localizations.dart';",
    "import '../../l10n/app_localizations_en.dart';",
    '',
    'extension MobileText on BuildContext {',
    '  String mobileText(String source, [Map<String, Object> values = const {}]) {',
    '    final l10n = Localizations.of<AppLocalizations>(this, AppLocalizations) ?? AppLocalizationsEn();',
    '    return switch (source) {',
  ];
  for (final entry in unique.entries) {
    final source = entry.key;
    final key = entry.value;
    // ICU messages are accessed through typed getters, not source lookup.
    if (RegExp(r'\{\w+,').hasMatch(source)) continue;
    if (_pluralSources.containsKey(source)) {
      lines.add(
        "      ${_quote(source)} => l10n.${_pluralSources[source]}(num.tryParse((values['value1'] ?? 0).toString()) ?? 0),",
      );
      continue;
    }
    final placeholders = RegExp(
      r'\{(\w+)\}',
    ).allMatches(source).map((match) => match.group(1)!).toSet();
    final metadata = catalog['@$key'] as Map<String, dynamic>?;
    final types = metadata?['placeholders'] as Map<String, dynamic>?;
    final arguments = placeholders
        .map((name) {
          final type = (types?[name] as Map<String, dynamic>?)?['type'];
          final value = "values[${_quote(name)}] ?? ''";
          if (type == 'String') return '($value).toString()';
          if (type == 'int' || type == 'num' || type == 'double') {
            return '$type.tryParse(($value).toString()) ?? 0';
          }
          return value;
        })
        .join(', ');
    final call = placeholders.isEmpty ? '' : '($arguments)';
    lines.add('      ${_quote(source)} => l10n.$key$call,');
  }
  lines.addAll([
    // A future missed registration must not crash a production screen. The
    // source contract tests reject unregistered authored literal call sites.
    '      _ => source,',
    '    };',
    '  }',
    '}',
    '',
  ]);
  File(
    '${root.path}/lib/shared/helpers/mobile_text.dart',
  ).writeAsStringSync(lines.join('\n'));
}
